name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
      - fork
  pull_request:
jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: cedrickring/golang-action@1.7.0
        with:
          args: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: false
